name: C++ CI with CMake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git
          sudo apt-get install -y extra-cmake-modules
          sudo apt-get install -y qt6-base-dev  # Qt6'yı yükler

      - name: Install ECM 6.0.0
        run: |
          # ECM 6.0.0'ı GitHub'dan indirip kuruyoruz
          git clone --branch master https://invent.kde.org/kde/extra-cmake-modules.git
          cd extra-cmake-modules
          mkdir build
          cd build
          cmake ..
          make
          sudo make install

      - name: Create build directory
        run: mkdir build

      - name: Run CMake & configure build
        run: cmake -B build/ --install-prefix ~/.local

      - name: Build with CMake
        run: cmake --build build/ --parallel && cmake --install build/
