name: C++ CI with CMake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: actions/setup-cmake@v3  # V2 yerine V3 kullanıyoruz
        with:
          cmake-version: '3.24.0'  # İhtiyacınıza göre versiyon seçin

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Create build directory
        run: mkdir build && cd build

      - name: Run CMake
        run: cmake ..

      - name: Build with CMake
        run: cmake --build .
